server:
  port: 8769
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: provider
          uri: http://localhost:8769
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1     #uri截取位置
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostAddrKeyResolver}'    #用于限流的键的解析器的 Bean 对象的名字。它使用 SpEL 表达式根据#{@beanName}从 Spring 容器中获取 Bean 对象。
                redis-rate-limiter.replenishRate: 1    #replenishRate，令牌桶每秒填充平均速率。
                redis-rate-limiter.burstCapacity: 3    #burstCapacity，令牌桶总容量。
        - id: consumer
          uri: lb://consumer
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1
  redis:
    database: 0
    host: localhost
    port: 6379

