server:
  port: 8763
spring:
  application:
    name: cloud-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411
    service:
      name: provider
  sleuth:
    sampler:
      probability: 1