server:
  port: 8763
spring:
  application:
    name: cloud-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        #配置 Sentinel dashboard 地址
        dashboard: localhost:8998
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411
    service:
      name: provider
  sleuth:
    sampler:
      probability: 1